---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maison-flacon
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./umami-route.yaml
