---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zwave-js-ui
  namespace: home
spec:
  dependsOn:
    - name: external-secrets-stores
      namespace: kube-system
    - name: volsync
      namespace: volsync-system
  components:
    - ../../../../components/volsync
  path: ./kubernetes/apps/home/zwave-js-ui/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: zwave-js-ui
      VOLSYNC_CLAIM: zwave-js-ui-config
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-block
