---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: old-sonarr-config
  namespace: media
  labels:
    app.kubernetes.io/name: old-sonarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ${CLUSTER_STORAGE_NFS}
