---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
  namespace: media
spec:
  timeout: 15m
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 6.5.2
      sourceRef:
        name: nextcloud
        kind: HelmRepository
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true
    nextcloud:
      extraVolumes:
        - name: hugepages
          emptyDir:
            medium: HugePages-2Mi
      extraVolumeMounts:
        - name: hugepages
          mountPath: /dev/hugepages
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
          hugepages-2Mi: 250Mi
        limits:
          cpu: 4000m
          memory: 6000Mi
          hugepages-2Mi: 250Mi
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init
          envFrom:
            - secretRef:
                name: &secret nextcloud-secret
      datadir: /var/www/data
      host: &host nextcloud.${SECRET_DOMAIN}
      extraEnv:
        - name: REDIS_HOST
          value: dragonfly.databases.svc.cluster.local
        - name: REDIT_HOST_PORT
          value: "6379"
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: *host
        - name: TRUSTED_PROXIES
          value: '10.0.0.0/8'
        - name: TZ
          value: ${TIMEZONE}
      existingSecret:
        enabled: true
        secretName: *secret
      securityContext:
        runAsUser: 588
        runAsGroup: 588
        runAsNonRoot: true
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.0.0.0/8',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          ); ?>
        misc.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'NC',
            'maintenance_window_start' => 2,
          ); ?>
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: *secret
        usernameKey: INIT_POSTGRES_USER
        passwordKey: INIT_POSTGRES_PASS
    ingress:
      enabled: true
      className: external
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      path: /
      pathType: Prefix
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
              service:
                name: nextcloud
                port: http
      tls:
        - hosts:
            - *host
          secretName: nextcloud-cert
    persistence:
      enabled: true
      storageClass: ${CLUSTER_STORAGE_BLOCK_SSD_3_REPLICA}
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data
        accessMode: ReadWriteMany
