apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-adminstxt
    namespace: gaming
stringData:
    Admins.txt: |
        76561197960287930
---
apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-gameusersettingsini
    namespace: gaming
stringData:
    GameUserSettings.ini: |
        SpectatorSettings=(bXRay=False,bXrayTails=True,bXrayTailsPlayerOnly=False,bShowControls=True,bMinimap=True,bTeamScores=True,bPlayerVitals=False)
        bDeathCamera=True
        [/Script/ModKit.ModIOClient]
        bHasUserAcceptedTerms=True
        AccessToken=TAljBI3MKIYAn8WaN0y59wPRw7fKSdAMfZ72Pcl8
