---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: storage
  labels:
    app.kubernetes.io/name: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Ti
  storageClassName: ${CLUSTER_STORAGE_NFS}
