---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  namespace: media
  labels:
    app.kubernetes.io/name: overseerr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ${CLUSTER_STORAGE_BLOCK_SSD_3_REPLICA}
