---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prohacker-valheim
  namespace: gaming
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prohacker-valheim-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: prohacker
