---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gate
  namespace: gate
spec:
  interval: 10m
  chart:
    spec:
      chart: gate-charts
      version: '0.75'
      sourceRef:
        kind: HelmRepository
        name: gate-charts
  values:
    celery:
      image: ${SECRET_DOCKER_USER}/celery_motion:latest
      persistence:
        enabled: true
        existingClaim: security-camera
    gate:
      image: ${SECRET_DOCKER_USER}/gate:latest
      persistence:
        existingClaim: gate
        securityClaim: security-camera
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
      clusterissuer: letsencrypt-production
      hostname: gate.${SECRET_DOMAIN}
      ingressClassName: external
      ingressClass: ''
    motion:
      image: ${SECRET_DOCKER_USER}/motion:latest
      motionNodePort: 9081
      persistence:
        enabled: true
        existingClaim: security-camera
    mysql:
      mysqlAllowEmptyPassword: false
      mysqlRootPassword: ${SECRET_GATE_MYSQL_PW}
      persistence:
        enabled: true
        existingClaim: mysql
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
      configurationFiles:
        sanity.cnf: |-
          [mysqld]
          sql_mode = NO_ENGINE_SUBSTITUTION
        time.cnf: |-
          [mysqld]
          default_time_zone=America/New_York
    rabbitmq:
      persistence:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: nfs-fileserv
        size: 8Gi
      auth:
        password: ${SECRET_GATE_RABBITMQ_PW}
        erlangCookie: ${SECRET_GATE_RABBITMQ_ERLANG_COOKIE}
      replicaCount: 1
