---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gate
  namespace: flux-system
spec:
  dependsOn:
    - name: pvc-media
    - name: external-secrets-stores
  path: ./kubernetes/apps/gate/gate/app
  prune: true
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
