---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: jellyfin
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44, 109, 65537]

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.8
            env:
              TZ: ${TIMEZONE}
              JELLYFIN_PublishedServerUrl: "https://jellyfin.${SECRET_DOMAIN}"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 1000m
                memory: 2Gi
              limits:
                memory: 24Gi

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    route:
      main:
        hostnames: ["jellyfin.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
        globalMounts:
          - path: /config
      media:
        existingClaim: videos
        globalMounts:
          - path: /media
      transcode:
        type: emptyDir
        globalMounts:
          - path: /config/transcodes
