---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.18.2
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  values:
    crds:
      enabled: true
    monitoring:
      enabled: true
    ingress:
      dashboard:
        ingressClassName: internal
        annotations:
        host:
          name: rook.${SECRET_DOMAIN}
          path: /
    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard = true
    cephClusterSpec:
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
      storage:
        useAllNodes: true
        useAllDevices: true
        config:
          osdsPerDevice: "1"
      resources:
        mgr:
          requests:
            cpu: 125m
            memory: 512Mi
          limits:
            memory: 1Gi
        mon:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            memory: 1Gi
        osd:
          requests:
            cpu: 200m
            memory: 4Gi
          limits:
            memory: 8Gi
        mgr-sidecar:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            memory: 200Mi
        crashcollector:
          requests:
            cpu: 15m
            memory: 64Mi
          limits:
            memory: 128Mi
        logcollector:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 1Gi
        prepareosd:
          requests:
            cpu: 250m
            memory: 50Mi
          limits:
            memory: 2Gi
        cleanup:
          requests:
            cpu: 250m
            memory: 100Mi
          limits:
            memory: 1Gi
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-block
      deletionPolicy: Delete
    cephBlockPools:
      - name: ceph-ssd-3-replica
        spec:
          failureDomain: host
          replicated:
            size: 3
          deviceClass: ssd
        storageClass:
          enabled: true
          name: ${CLUSTER_STORAGE_BLOCK_SSD_3_REPLICA}
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
      - name: ceph-hdd-3-replica
        spec:
          failureDomain: host
          replicated:
            size: 3
          deviceClass: hdd
        storageClass:
          enabled: true
          name: ${CLUSTER_STORAGE_BLOCK_HDD_3_REPLICA}
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephFileSystems:
      - name: ceph-ssd-3-replica-filesystem
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                cpu: 35m
                memory: 64M
              limits:
                memory: 600M
          deviceClass: ssd
        storageClass:
          enabled: true
          isDefault: false
          name: ${CLUSTER_STORAGE_FILESYSTEM_SSD_3_REPLICA}
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          mountOptions: []
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephFilesystemVolumnSnapshotClass:
      enabled: true
      name: csi-ceph-fs
      deletionPolicy: Delete
    cephObjectStores:
      - name: rook-ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
          preservePoolsOnDelete: true
          gateway:
            port: 80
            resources:
              requests:
                cpu: 100m
                memory: 128M
              limits:
                memory: 2Gi
            instances: 1
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ${CLUSTER_STORAGE_BUCKET_SSD_3_REPLICA}
          reclaimPolicy: Delete
          parameters:
            region: us-east-1