# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Zg7SymgXUy7svR0HmCj6uxyxaGIDufe9FwSmR4tvwSY=,iv:WPhsc5Q7cdYa2wKw9lpwooZip22Zbv7mxAPDegP3Huc=,tag:wQ5qaRgdplP51f3qsDzSEg==,type:str]
sops:
  age:
    - recipient: age1x8yqlz3z8ck28vcmyr07tfq85jpr2gc37w0r6y9jj6z69agnvvpsvnw3wz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubVBpdEVqYXBHdkxOOEIr
        c0w1dDFBbGo3Y05rYytBSjhHdUhYR0VsVzJrCnJiS1dTQUVzY0UwYkkvZkw1TjA4
        RDlCd2ZFUzlnbHhpbUcwQ3VBWVpSZjQKLS0tIGNJcER1dHpiNnYrbm4rakVsdWFz
        RVdiSlZqZDI3RmFkZXBybVpCeXRQVWcKdBmtU1uEii25x8SfKoqeoIPLcSdVIt9k
        0nHFGDkr4aqb+cdQuy7Gm0rq6PbxVexH2B47Wpqyy/7HDQhaql6l5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-11T21:26:14Z"
  mac: ENC[AES256_GCM,data:m+ykEieR+D3jpaUd4QE94HVZwKbmAaPEw3hAfN+y+T+YLQOKhJMeV9qkdKk1yoMku6k5wxK52nEpmsot8YHETKdNISpgtr/MhkBVA9jjPcfNeBcUfbAI9zXvjsUSHcGm6yGgHxWr1VBtHWd/JB/mnYr7kzkEApjPknlrLpwHofE=,iv:7DGY758z4akUloNDEIANcYEtCuEGROaiEQwiYyjpDNo=,tag:UQQ+GpZfUmVTBqtIYS+TQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
