---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: asok-disk0
  namespace: openebs-system
spec:
  node: asok
  disks: ["aio:///dev/disk/by-id/wwn-0x5000c500940dd1cf?blk_size=4096"]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: asok-disk1
  namespace: openebs-system
spec:
  node: asok
  disks: ["aio:///dev/disk/by-id/wwn-0x5000c500942abdc3?blk_size=4096"]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: asok-disk3
  namespace: openebs-system
spec:
  node: asok
  disks: ["aio:///dev/disk/by-id/wwn-0x5000c5009499b667?blk_size=4096"]

