---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: phil-disk0
  namespace: openebs-system
spec:
  node: phil
  disks: ["/dev/disk/by-id/ata-Samsung_SSD_870_EVO_2TB_S753NS0W927885N"]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: phil-disk1
  namespace: openebs-system
spec:
  node: phil
  disks: ["/dev/disk/by-id/ata-Hitachi_HUA723020ALA640_MK0271YGKKWN0G"]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: phil-disk2
  namespace: openebs-system
spec:
  node: phil
  disks: ["/dev/disk/by-id/ata-CT1000MX500SSD1_2132E5BF1E79"]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: phil-disk3
  namespace: openebs-system
spec:
  node: phil
  disks: ["/dev/disk/by-id/ata-ST3000DM001-1ER166_Z502337B"]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: phil-disk4
  namespace: openebs-system
spec:
  node: phil
  disks: ["/dev/disk/by-id/ata-PNY_CS900_500GB_SSD_PNY2119210513010C4C8"]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: phil-disk5
  namespace: openebs-system
spec:
  node: phil
  disks: ["/dev/disk/by-id/ata-TOSHIBA_DT01ACA300_X4FNK8BGS"]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: phil-disk6
  namespace: openebs-system
spec:
  node: phil
  disks: ["/dev/disk/by-id/ata-SanDisk_SDSSDH3_512G_21120U804005"]
