---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: thing1
  namespace: openebs-system
spec:
  node: thing1
  disks: ["/dev/disk/by-id/ata-CT1000MX500SSD1_2336E8746026", "/dev/disk/by-id/ata-WDC_WD40EFZX-68AWUN0_WD-WX32DC02VFAD", "/dev/disk/by-id/ata-ST3000DM001-1CH166_Z1F50MC6", "/dev/disk/by-id/ata-ST3000DM001-1CH166_Z1F512QF", "/dev/disk/by-id/ata-SanDisk_SDSSDH3_1T02_20347B800262", "/dev/disk/by-id/ata-WDC_WDBNCE0010PNC_214026800890"]
