---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatehouse
  namespace: gate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatehouse-secret
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        MQTT_USERNAME: "{{ .MQTT_USERNAME }}"
        MQTT_PASSWORD: "{{ .MQTT_PASSWORD }}"
  dataFrom:
    - extract:
        key: gatehouse
