---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: space-exploration-factorio
  namespace: gaming
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: space-exploration-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        USERNAME: "{{ .FACTORIO_USERNAME }}"
        TOKEN: "{{ .FACTORIO_TOKEN }}"
  dataFrom:
    - extract:
        key: factorio
