---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-clean-slate
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${CLUSTER_STORAGE_BLOCK_SSD_3_REPLICA}
  resources:
    requests:
      storage: 10Gi