---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pvc-media
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/_pvc/media
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
