---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: old-radarr-config
  namespace: media
  labels:
    app.kubernetes.io/name: old-radarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ${CLUSTER_STORAGE_NFS}
