---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana/ks/yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./namespace.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./thanos/ks.yaml
  - ./vector/ks.yaml
