---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave-js-ui
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
    controllers:
      zwave-js-ui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: zwavejs/zwave-js-ui
              tag: 9.30.1
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 10m
                memory: 100M
              limits:
                memory: 256M
            securityContext:
              privileged: true
        pod:
          nodeSelector:
            kubernetes.io/hostname: "nuc1"
    service:
      app:
        controller: zwave-js-ui
        ports:
          http:
            port: &port 8091
          websocket:
            port: 3000
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:zwave
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host zwave.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - hosts:
              - *host
            secretName: zwave-js-ui-cert
    persistence:
      config:
        enabled: true
        existingClaim: zwave-js-ui-config
        globalMounts:
          - path: /usr/src/app/store
    resources:
      requests:
        smarter-devices/ttyACM0: 1
        cpu: 10m
        memory: 100M
      limits:
        smarter-devices/ttyACM0: 1
        memory: 512M
