apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:KQXq3wpSP6nTmWDkG6VxdvSq+0xt7TwAOn1+4u01SMsUsAcHIidv0DAeDGuqfmICD//WpPTjy9yJFZQdMLUuSdzf8f5AjYOpyUfVqFwHHHmzw+ryg6/gpW7BwR5SLw==,iv:mxAZwem3WBaNaQD7rzoD4bRBqpn7UVhrXQ8q6+stijs=,tag:JCbw9jJw3N8Ah7GnnXHyDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10xxw4pck9kzfespa7g53ktcj3gettukrd6v45s9lq8fsh5gyv5vq5y8vv5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSWF6QjIwMC90endGZGw2
            VXZSM2hEbkZaWmVWeTF0VnkwUGhhRUFTOFFvCndBM0dMc05sY2k1R1RSNHRIVHk2
            eEhwY0c1Z0haMDYxZXNacVJLNW0yR1UKLS0tIHVLTzlxRHArd0dJZkxReGhVSVBI
            L0tycVo2ZElRdG5tYXdKQWF6aHJaMDgKJDrqhyYaxENlFxJVPtcNVnzaRSWLDRmh
            6AGovQOMhTSE7YaRXlfwea1iLe1oQDp7Z27BWpok9PFikejUawWSdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T03:58:26Z"
    mac: ENC[AES256_GCM,data:uDVbs7EuI1jKu+Z7uHSJtaZgtz7BB2pAMTvQND59S83oJd6A5hhjpogTlMsQ9eD2fMn8Z7BLXgshUzUWtW9Hcm7CA4g6zXUZGFgbMvqIklHYeHVAwRVeKzCEuq1OOU5itW80AaWfbrRThc4pLMr+eKobVOM2l1WwdyKSdZkOQr4=,iv:C162M40vj1GIOzRIv0x6cVDaPD5puUHUaMvbfJAipa0=,tag:04XSEpIcWKHOIbnyb+I37g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
