apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:XimDeWJAZFDS+jRSrpkMHE0gF061S5ISpCe3oL/r0dZUJ4J/yt5JZ/IRt4/lP2ZOVehXtMAMIeQj5DqHDVO8m+TUI0htSV68QGK3Uz9ZEzKM1sV2ZfKO5EPRmXXfTg==,iv:tx4DgibwhAk219CJ6LXOwDrSX63C/s95CCUJRWHgSoc=,tag:pL1SBLvCjPPlozkXyCM0/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10xxw4pck9kzfespa7g53ktcj3gettukrd6v45s9lq8fsh5gyv5vq5y8vv5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdUJHYnZBZGFJQkJObFRl
            UjRrZERhcGdXc2lGc0o4Q3NtWTdBb25Db2xFCnVIKzFwa3VlenZsWlVkL2hWeWhW
            alI2V3Y2ZGRuOC9XY1l0Q21xcmFnSW8KLS0tIFg4SHZObWJxTXNLekdhZG1YTXll
            Z2c4Z3RZZ3Fjbm1zak5XYkE4TTQxTWMK43w4jCoJkh1b0I64kPpc71G3wH8eOEfM
            f28Sgu5wA7iVTy61cqyvxogkP/GbR1RcVVGdIExGvKLYBHrgo2CUSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-04T06:27:26Z"
    mac: ENC[AES256_GCM,data:PVYRr9a0O+d/BDMaLfzJziBnOtuo9Kr15p54jLr+hGs/uGpbqcLQtybVx3/5NaH4cjFn6ohbQYH9Qu33/0yia0NQjuEUpzKRRFmjzSvNNTaHK4y0QWftam5H5a+eLI4I61cBWoQxBQBwSAh9Ipo00IRrd0ulYrTiax4EREC+aco=,iv:A7v5adwjusSG4w3MrgH0PX9EA3aVsxkVosbL4moYU3Y=,tag:jto2mGeLcBEFWwpF20EFuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
