---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44    # video
          - 109   # render
          - 65537 # media ro

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.42.1.10060@sha256:04563be281364ba2462285aacb2ca13d7ef7e1d0b19e1203f4c19b4a56840c5c
            env:
              TZ: ${TIMEZONE}
              ADVERTISE_IP: http://${PLEX_LB_IP}:32400,https://plex.${SECRET_DOMAIN}:443
              ALLOWED_NETWORKS: '10.0.0.0/8'
              HOSTNAME: 'plex'
            resources:
              requests:
                cpu: 1000m
                memory: 2000M
              limits:
                memory: 10000M

    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          io.cilium/lb-ipam-ips: ${PLEX_LB_IP}
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          hajimari.io/icon: mdi:plex
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host plex.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: 32400
        tls:
          - hosts:
              - *host
            secretName: plex-cert

    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
      media:
        existingClaim: videos
        globalMounts:
          - path: /media
      music:
        existingClaim: music
        globalMounts:
          - path: /music
