---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frigate
  namespace: home
spec:
  dependsOn:
    - name: home-assistant
    - name: external-secrets-stores
      namespace: kube-system
    - name: volsync
      namespace: volsync-system
  components:
    - ../../../../components/volsync
  path: ./kubernetes/apps/home/frigate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: frigate
      VOLSYNC_CLAIM: frigate-data
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-block
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
