apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:BAa94MKt3Ec6SvwwyAEXAkJwtYOrBB26DOmMX56si9M=,iv:0vknDCsECpHS7p0GDfLbYYSTBgLUZkEsYOwBFOmZCw8=,tag:7PkK8eMU4iHtrKaX1jwhSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10xxw4pck9kzfespa7g53ktcj3gettukrd6v45s9lq8fsh5gyv5vq5y8vv5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSTJrYXdMaWxBeTljZWhy
            WDNQTitob0svUGlIajZhalpBOFlybHhCT1cwCmJ0VWNKY0FDMXRWOTRSV0ZkdkJn
            WkJ6eHgvN0F3d29BQlJKdFFZMUc3VDAKLS0tIEljYWgyTkZFNW1tV1VBTVpKMklK
            VFhPK2xzc3NNN3ZTRkY4RnBHRTdFQXMKMgRVI0jveILpxDrxONlumFjMDf9dDKsF
            PeidL98vLwwBQBKPt3vPrpVPjhdjmFRoh/HtRvQ+syTrTVEwXUiW9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T03:58:26Z"
    mac: ENC[AES256_GCM,data:1QxXbkdVCZ+7rRBvL4M5YPJhqJdxYOEOqTwbQgaAVSQ1bth8xJzdJJex0vPuVb6LHkWBVpz6CXOBOJjgS/FuPAvdanO69tImAYY9jL5Wa3Fi4FvsOFOKEvAvVrVHriusO9KySAQqjxlsXkw+ZAwxFisZNXXu+jpG8mJlYczEaOo=,iv:bbI3nsJhLccpnIKxp4EESGIKFmrjRpi7F/EH6TCSnk0=,tag:zEXjseiehILdwfGhd8uCjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
