apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:zJUbq8KehOGlw34xG/6/vQ7knUf/lduoegaqV0crrd4=,iv:JvVRyGo1Uy92MTjdACO1qZBIxqAA4CcgZU+y2/NWo3Q=,tag:R4ywIRD7OTozID+c6WYssQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10xxw4pck9kzfespa7g53ktcj3gettukrd6v45s9lq8fsh5gyv5vq5y8vv5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d3d2WlJkKytJcFFxNnZi
            MElwZDVnNGgrRTFxL3p6VXhiM29xdmtGOWpZCi9CenR5ZHJqQTVHL2xWYk5NaUZ1
            L2dqQVZySXVWYWVCU3BMS1JVdHNUR00KLS0tIGhiOXJPa0J2R05tYUFvN25kb2Vx
            TnA0eGZKMzBpK0pqT01nVkVtak14WFUKJ0DQRMJBl4fYmMClLg77xhXQPO15eS/O
            LYubP/QIdvquMqw8K0Ln4cDKpZs2wrixF5v01Y38NuafVjRrfYPdug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T02:37:55Z"
    mac: ENC[AES256_GCM,data:6sgCsNxV+r6rjiwMqsop8O4Q9m8U4c80YmZWLVQU6UYCevIfINRWZv2ZPIBdG7TbTnLVcCDrrwaSwcvmzwN3xLvgosFi+/6w9FehCfS2Cdp9voFtbKmVCGdtX9yvhvriMNvjGsY0s2cbgs4dHs8HnhpHAg/Amie8OQMGHtfySkY=,iv:uVBbupvdJt1F80CR7C2UVGxvo2uA2mmDjye8r3DXkWA=,tag:lz2sOpZf01rD/2xiCZWA9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
