apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:RYFfznji278N6VVOdzwZKXTupTQzWBY/JlYY6MGk9Ok=,iv:ytY1yiVQKgaDYf87oK/Kmw/YiqQadkQI4ZNKiLxmLzk=,tag:RcaAncxyF27TbCHNtTUQ8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10xxw4pck9kzfespa7g53ktcj3gettukrd6v45s9lq8fsh5gyv5vq5y8vv5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeERyREhtbW81aTkxN2hh
            bWZKWTVvcGt4OWFQVUxxdGFMTVhqVG5BMHpFCnM0MkJPWkp5UGV3NmF1WUZtY1Bq
            ZGlvTldabk1oY0tGRDMvOFZURjdrRmsKLS0tIEhSL1l0dENqNU8zVERpenFYb3Jq
            WFAwSGFSMlYxWmUvSHc2bmtuSmRtMDgKKfgoOfz09K1/sNskbEfeDOXGj6t8+TFr
            545TXi+zHkadhmuc/wMMmA58JgkXhF+UAZlJhpYBP1J4BMMf5EShPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-04T06:27:26Z"
    mac: ENC[AES256_GCM,data:IN4scIR7r1EB3Jl99XyGxZm82EHsLh4YQnulE+B+dsKEjDq0U9bAzZGmYiHLpP1fjizWf4f6omKa84UPsO+2N8VIKhUxIceMURfi+UpfkaaSzpp9B8DabdUVIz5MacK7PSGnHptO0XnyEIrW/NjbNK8RCCQkUMnGba2YVPVDz08=,iv:QXH+uNv4rLkoTruquGG5UzE4UaNpmRkBT+6uy1QT8N4=,tag:/ZhzE+Gz7tGaJjM3PX96yA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
