---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-r2
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "0 0 * * *"
  restic:
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-ceph-ssd-3-replica}"
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${APP_UID:-568}
      runAsGroup: ${APP_GID:-568}
      fsGroup: ${APP_GID:-568}
    pruneIntervalDays: 7
    repository: ${APP}-volsync-r2
    retain:
      daily: 7
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-block}"
    # Commented out to fix scheduling issues - multiple VolSync jobs can now run on same node
    # moverAffinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - topologyKey: kubernetes.io/hostname
    #         labelSelector:
    #           matchLabels:
    #             app.kubernetes.io/created-by: volsync
    #         namespaceSelector:
    #           matchExpressions:
    #             - key: kubernetes.io/metadata.name
    #               operator: Exists
