apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:MHNxsL6hJ2sKDLsYPPs=,iv:F1cHwCGIh7AkB/dLlvkjZJU21r6Msds6Q8GioAB+smU=,tag:/D+xNfF93SzhMYM9R6eovA==,type:str]
sops:
  age:
    - recipient: age1x8yqlz3z8ck28vcmyr07tfq85jpr2gc37w0r6y9jj6z69agnvvpsvnw3wz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eFZxdEhFOUxZU3k4Sk5o
        a1NJazNMTEhENnFheVloQXVwSnB2WmYwYlg4Cm1QOUpLUmJmOWE0SERtL0NMQlFF
        Y3BFbHIyMVZBU1MxWlB2ZXBjR2h4d3MKLS0tIHZUdHdPV1k0akhvazJwZ0dPTFpH
        S2N1MVBaR0F4elAvWHcxOThvSi9nK00Kv+J8QR63Ktc1amqfdGH7ki8gztXuDW+S
        acxb49EKP6COIOhWqtFJ5R0WauRBApBdVOp5SrhHpjonF6JhJ9vh/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-11T22:56:48Z"
  mac: ENC[AES256_GCM,data:xC1eCRiCzSpvMj2LG2PummYg1eB/xeDR0soFV1pMjeZb3u53wzmvLykPG4BHz636mXRlWbD92AWqVcDwzqS+TBgz+TPOeVyXb2KkDKcyQPlVA3nnuy2tW/+gkND4VoD852t2uCl5GwKL5wegokvCRcGAmkDZHN6/vuGGzV68REg=,iv:UKfpWBfomvmRbst2nQYv2tPHHFirjiJSMmxC4KlbaHI=,tag:uLvWmtnKKdg+k7PaS4tymw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
