---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: volsync
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: snapshot-controller
      namespace: volsync-system
  values:
    manageCRDs: true
    metrics:
      disableAuth: true
    image:
      repository: &image quay.io/backube/volsync
      tag: &tag 0.16.0@sha256:0d03a6aad57569eba2c0eaa0848cf4a908d9744b372ff2224bb291a320f36d76
    restic:
      repository: *image
      tag: *tag
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: volsync
              spec:
                template:
                  spec:
                    priorityClassName: system-cluster-critical