---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: volsync
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: snapshot-controller
      namespace: volsync-system
  values:
    manageCRDs: true
    metrics:
      disableAuth: true
    image:
      repository: &image quay.io/backube/volsync
      tag: &tag 0.15.0@sha256:4fedd41b3101dde090542009c4177f703d241bf4760d1767bd9df08fd8fd93a4
    restic:
      repository: *image
      tag: *tag
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: volsync
              spec:
                template:
                  spec:
                    priorityClassName: system-cluster-critical