---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft
  namespace: gaming
spec:
  path: ./kubernetes/apps/gaming/minecraft/app
  prune: true
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: rook-ceph-cluster
      namespace: storage
  components:
    - ../../../../components/volsync
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
    substitute:
      APP: minecraft
      VOLSYNC_CLAIM: minecraft-data
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-block
      VOLSYNC_CAPACITY: 100Gi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: armadillo
  namespace: gaming
spec:
  path: ./kubernetes/apps/gaming/minecraft/armadillo
  prune: true
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: rook-ceph-cluster
      namespace: storage
  components:
    - ../../../../components/volsync
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
    substitute:
      APP: armadillo
      VOLSYNC_CLAIM: armadillo-data
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-block
      VOLSYNC_CAPACITY: 100Gi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cicada
  namespace: gaming
spec:
  path: ./kubernetes/apps/gaming/minecraft/cicada
  prune: true
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: rook-ceph-cluster
      namespace: storage
  components:
    - ../../../../components/volsync
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
    substitute:
      APP: cicada
      VOLSYNC_CLAIM: cicada-data
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-block
      VOLSYNC_CAPACITY: 100Gi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: scorpion
  namespace: gaming
spec:
  path: ./kubernetes/apps/gaming/minecraft/scorpion
  prune: true
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: rook-ceph-cluster
      namespace: storage
  components:
    - ../../../../components/volsync
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
    substitute:
      APP: scorpion
      VOLSYNC_CLAIM: scorpion-data
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-block
      VOLSYNC_CAPACITY: 100Gi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: skyblock
  namespace: gaming
spec:
  path: ./kubernetes/apps/gaming/minecraft/skyblock
  prune: true
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: rook-ceph-cluster
      namespace: storage
  components:
    - ../../../../components/volsync
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
    substitute:
      APP: skyblock
      VOLSYNC_CLAIM: skyblock-data
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-block
      VOLSYNC_CAPACITY: 100Gi
