---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex
  namespace: media
spec:
  dependsOn:
    - name: pvc-media
    - name: external-secrets-stores
      namespace: kube-system
    - name: volsync
      namespace: volsync-system
  components:
    - ../../../../components/volsync
  path: ./kubernetes/apps/media/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
    substitute:
      APP: plex
      VOLSYNC_CLAIM: plex-config
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-block
      VOLSYNC_CAPACITY: 250Gi
