---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minion-valheim
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-fileserv
  resources:
    requests:
      storage: 10Gi